"""
JSONL training data validation tests (P11-E2-T3, DJ-054).

Skipped when training JSONL files are absent (generated by make generate-training-jsonl).
These tests validate the generated data quality without requiring LLM or live services.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

_DATA_DIR = Path(__file__).resolve().parent.parent.parent / "data" / "training"
_TECH_JSONL = _DATA_DIR / "technical_max_return_60d.jsonl"
_FUND_JSONL = _DATA_DIR / "fundamental_risk_adjusted_60d.jsonl"

_TECH_EXISTS = _TECH_JSONL.exists()
_FUND_EXISTS = _FUND_JSONL.exists()


def _load_jsonl(path: Path) -> list[dict]:
    return [json.loads(line) for line in path.read_text().splitlines() if line.strip()]


# ---------------------------------------------------------------------------
# Technical JSONL tests
# ---------------------------------------------------------------------------


@pytest.mark.skipif(not _TECH_EXISTS, reason="technical_max_return_60d.jsonl not yet generated")
def test_technical_jsonl_min_examples() -> None:
    """Technical training file has at least 400 examples."""
    examples = _load_jsonl(_TECH_JSONL)
    assert len(examples) >= 400, (
        f"Expected >= 400 examples; got {len(examples)}. "
        "Run: make generate-reference-strategies then generate-training-jsonl"
    )


@pytest.mark.skipif(not _TECH_EXISTS, reason="technical_max_return_60d.jsonl not yet generated")
def test_technical_class_balance() -> None:
    """Buy examples are between 25% and 50% of the total dataset."""
    examples = _load_jsonl(_TECH_JSONL)
    decisions = []
    for ex in examples:
        assistant = next((m for m in ex["messages"] if m["role"] == "assistant"), None)
        if assistant:
            import contextlib
            with contextlib.suppress(json.JSONDecodeError):
                decisions.append(json.loads(assistant["content"]).get("decision", "Hold"))
    n_buy = decisions.count("Buy")
    ratio = n_buy / len(decisions) if decisions else 0
    assert 0.25 <= ratio <= 0.50, (
        f"Buy class ratio {ratio:.2%} outside [25%, 50%] (class imbalance)"
    )


@pytest.mark.skipif(not _TECH_EXISTS, reason="technical_max_return_60d.jsonl not yet generated")
def test_all_technical_examples_have_valid_assistant_json() -> None:
    """Every assistant content in the technical JSONL parses as valid JSON."""
    examples = _load_jsonl(_TECH_JSONL)
    for i, ex in enumerate(examples):
        assistant = next(m for m in ex["messages"] if m["role"] == "assistant")
        try:
            payload = json.loads(assistant["content"])
        except json.JSONDecodeError as exc:
            pytest.fail(f"Example {i}: assistant content is not valid JSON: {exc}")
        assert "decision" in payload, f"Example {i}: missing 'decision' field"
        assert payload["decision"] in ("Buy", "Hold", "Sell"), (
            f"Example {i}: invalid decision {payload['decision']!r}"
        )


@pytest.mark.skipif(not _TECH_EXISTS, reason="technical_max_return_60d.jsonl not yet generated")
def test_technical_messages_structure() -> None:
    """Each example has system/user/assistant roles in the correct order."""
    examples = _load_jsonl(_TECH_JSONL)
    for i, ex in enumerate(examples[:10]):  # spot check first 10
        assert "messages" in ex, f"Example {i}: missing 'messages' key"
        roles = [m["role"] for m in ex["messages"]]
        assert roles == ["system", "user", "assistant"], (
            f"Example {i}: expected [system, user, assistant], got {roles}"
        )


# ---------------------------------------------------------------------------
# Fundamental JSONL tests
# ---------------------------------------------------------------------------


@pytest.mark.skipif(not _FUND_EXISTS, reason="fundamental_risk_adjusted_60d.jsonl not yet generated")  # noqa: E501
def test_fundamental_jsonl_min_examples() -> None:
    """Fundamental training file has at least 400 examples."""
    examples = _load_jsonl(_FUND_JSONL)
    assert len(examples) >= 400, f"Expected >= 400 examples; got {len(examples)}"


@pytest.mark.skipif(not _FUND_EXISTS, reason="fundamental_risk_adjusted_60d.jsonl not yet generated")  # noqa: E501
def test_all_fundamental_examples_have_valid_assistant_json() -> None:
    """Every assistant content in the fundamental JSONL parses as valid JSON."""
    examples = _load_jsonl(_FUND_JSONL)
    for i, ex in enumerate(examples):
        assistant = next(m for m in ex["messages"] if m["role"] == "assistant")
        try:
            payload = json.loads(assistant["content"])
        except json.JSONDecodeError as exc:
            pytest.fail(f"Example {i}: not valid JSON: {exc}")
        assert "decision" in payload
        assert payload["decision"] in ("Buy", "Hold", "Sell")
