"""
Unit tests for technical_compliance_v2.jsonl (P12-E0-T1, DJ-061).

Skipped when the file is absent (generated by:
  uv run python scripts/archive/generate_compliance_examples.py).

The tests validate that the augmented compliance training file has:
  - >= 200 examples (target ratio fix: 0.19% -> ~0.75%)
  - Valid JSONL format (one JSON object per line)
  - Structurally valid assistant messages (decision, confidence, rationale, key_concern)
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

_DATA_DIR = Path(__file__).resolve().parent.parent.parent / "data" / "training"
_V2_JSONL = _DATA_DIR / "technical_compliance_v2.jsonl"
_EXISTS = _V2_JSONL.exists()

_SKIP_REASON = (
    "technical_compliance_v2.jsonl not yet generated. "
    "Run: uv run python scripts/archive/generate_compliance_examples.py"
)


def _load_jsonl(path: Path) -> list[dict]:
    return [json.loads(line) for line in path.read_text().splitlines() if line.strip()]


# ---------------------------------------------------------------------------
# Count
# ---------------------------------------------------------------------------


@pytest.mark.skipif(not _EXISTS, reason=_SKIP_REASON)
def test_technical_compliance_v2_count_gte_200() -> None:
    """technical_compliance_v2.jsonl must have at least 200 examples (DJ-061)."""
    examples = _load_jsonl(_V2_JSONL)
    assert len(examples) >= 200, (
        f"Expected >= 200 compliance examples; got {len(examples)}. "
        "Root cause: insufficient synthetic generation from OHLCV data."
    )


# ---------------------------------------------------------------------------
# JSONL format
# ---------------------------------------------------------------------------


@pytest.mark.skipif(not _EXISTS, reason=_SKIP_REASON)
def test_technical_compliance_v2_jsonl_format() -> None:
    """Each line must be a valid JSON object with the mlx_lm messages structure."""
    lines = [ln for ln in _V2_JSONL.read_text().splitlines() if ln.strip()]
    for i, line in enumerate(lines):
        try:
            obj = json.loads(line)
        except json.JSONDecodeError as exc:
            pytest.fail(f"Line {i}: not valid JSON: {exc}")
        assert "messages" in obj, f"Line {i}: missing 'messages' key"
        messages = obj["messages"]
        assert isinstance(messages, list), f"Line {i}: 'messages' must be a list"
        roles = [m.get("role") for m in messages]
        assert "system" in roles, f"Line {i}: missing system message"
        assert "user" in roles, f"Line {i}: missing user message"
        assert "assistant" in roles, f"Line {i}: missing assistant message"


# ---------------------------------------------------------------------------
# Schema validation
# ---------------------------------------------------------------------------


@pytest.mark.skipif(not _EXISTS, reason=_SKIP_REASON)
def test_technical_compliance_v2_assistant_schema() -> None:
    """Every assistant content must have decision, confidence, rationale, key_concern."""
    examples = _load_jsonl(_V2_JSONL)
    required_fields = {"decision", "confidence", "rationale", "key_concern"}
    valid_decisions = {"Buy", "Hold", "Sell"}

    for i, ex in enumerate(examples):
        assistant = next(
            (m for m in ex.get("messages", []) if m.get("role") == "assistant"),
            None,
        )
        assert assistant is not None, f"Example {i}: no assistant message"

        try:
            payload = json.loads(assistant["content"])
        except json.JSONDecodeError as exc:
            pytest.fail(f"Example {i}: assistant content is not valid JSON: {exc}")

        missing = required_fields - set(payload.keys())
        assert not missing, f"Example {i}: missing fields {missing}"

        assert payload["decision"] in valid_decisions, (
            f"Example {i}: invalid decision {payload['decision']!r}"
        )
        assert 0.0 <= float(payload["confidence"]) <= 1.0, (
            f"Example {i}: confidence {payload['confidence']} out of [0, 1]"
        )
        assert payload["rationale"].strip(), f"Example {i}: empty rationale"
        assert payload["key_concern"].strip(), f"Example {i}: empty key_concern"
