"""
Unit tests for the Phase 3 baseline fixture (P3-E5-T2, T3, T4).

These tests validate the structure and content of the baseline fixture produced by
scripts/run_phase3_baseline.py. They are skipped automatically when the fixture does
not exist -- the fixture is generated by running the baseline script with LM Studio live.

To generate the fixture:
    uv run python scripts/run_phase3_baseline.py
"""

import json
from pathlib import Path

import pytest

_FIXTURE_PATH = Path(__file__).parent.parent / "fixtures" / "baseline" / "phase3_baseline.json"

pytestmark = pytest.mark.skipif(
    not _FIXTURE_PATH.exists(),
    reason="phase3_baseline.json not generated yet -- run scripts/run_phase3_baseline.py",
)


@pytest.fixture(scope="module")
def baseline() -> dict:
    with open(_FIXTURE_PATH, encoding="utf-8") as f:
        return json.load(f)


def test_baseline_fixture_exists():
    assert _FIXTURE_PATH.exists(), "phase3_baseline.json must exist"


def test_baseline_has_required_top_level_keys(baseline):
    assert "metadata" in baseline
    assert "analyses" in baseline
    assert "metrics" in baseline


def test_compliance_rate_meets_threshold(baseline):
    compliance = baseline["metrics"]["compliance_rate"]
    assert compliance >= 0.90, f"compliance_rate {compliance} is below 0.90 threshold"


def test_all_three_tickers_present(baseline):
    analyses = baseline["analyses"]
    assert "AAPL" in analyses
    assert "JPM" in analyses
    assert "XOM" in analyses


def test_each_analysis_has_valid_decision(baseline):
    for ticker, analysis in baseline["analyses"].items():
        signal = analysis.get("signal")
        if signal is None:
            continue
        assert signal["decision"] in ("Buy", "Hold", "Sell"), (
            f"{ticker}: invalid decision {signal['decision']!r}"
        )


def test_each_analysis_has_valid_confidence(baseline):
    for ticker, analysis in baseline["analyses"].items():
        signal = analysis.get("signal")
        if signal is None:
            continue
        conf = signal["confidence"]
        assert 0.0 <= conf <= 1.0, f"{ticker}: confidence {conf} out of [0, 1]"


def test_metadata_has_required_fields(baseline):
    meta = baseline["metadata"]
    for field in ("phase", "model", "prompt_version", "data_as_of", "run_date", "hifi_commit"):
        assert field in meta, f"metadata missing field: {field}"


def test_metrics_has_required_fields(baseline):
    metrics = baseline["metrics"]
    for field in ("compliance_rate", "hallucinated_numbers", "data_gaps_acknowledged",
                  "mean_call_id_coverage", "mean_latency_ms", "n_analyses"):
        assert field in metrics, f"metrics missing field: {field}"
